services:
  hollyb_server_db:
    image: postgres:16-alpine
    container_name: ${PACKAGE_NAME}_postgres
    restart: unless-stopped
    profiles:
      - prod
      - dev
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      hollyb_network:
        aliases:
          - db

  server:
    image: ${DOCKER_USERNAME}/${PACKAGE_NAME}:${PACKAGE_VERSION}
    container_name: ${PACKAGE_NAME}_server
    restart: unless-stopped
    profiles:
      - prod
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      NODE_ENV: production
    # expose:
    #   - '5000'
    ports:
      - '5000:5000'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:5000/health || exit 1']
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      hollyb_server_db:
        condition: service_healthy
    networks:
      - hollyb_network

  # caddy:
  #   image: caddy:2-alpine
  #   container_name: ${PACKAGE_NAME}_caddy
  #   restart: unless-stopped
  #   profiles:
  #     - prod
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '443:443/udp'
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     server:
  #       condition: service_healthy
  #   networks:
  #     - hollyb_network
  #     - hollyb_shared_network

networks:
  hollyb_network:
    driver: bridge

volumes:
  postgres_data:
  # caddy_data:
  # caddy_config:
