
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hollyb_db
      POSTGRES_USER: hollyb_user
      POSTGRES_PASSWORD: hollyb_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: